name: ItemsAdderBlocksInjector
version: 0.0.18
main: dev.lone.blocksinjector.Main
api-version: 1.13
load: STARTUP
softdepend:
  - Iris
depend:
  - ItemsAdder
  - ViaVersion
libraries:
  - beer.devs:FastNbt-jar:1.4.8