name: ItemsAdderBlocksInjector
version: 0.0.20
main: dev.lone.blocksinjector.Main
api-version: 1.13
load: STARTUP
softdepend:
  - Iris
depend:
  - ItemsAdder
  - ViaVersion
libraries-libby:
  - beer.devs:FastNbt-jar:1.4.10