name: ItemsAdderBlocksInjector
version: 0.0.2
main: dev.lone.blocksinjector.Main
api-version: 1.13
load: STARTUP
depend:
  - ItemsAdder
  - ViaVersion
  - Iris
softdepend:
  - FastAsyncWorldEdit
  - WorldEdit